name = "ilikeorangutans"
license = "MIT"
licenselink = "https://github.com/ilikeorangutans/ilikeorangutans-hugo-theme/blob/master/LICENSE.md"
description = ""
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.38"

[author]
  name = "Jakob Külzer"
  homepage = "https://ilikeorangutans.github.io"
